---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 and php packages - Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: remove apache2 and php packages - CentOS
    dnf:
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"

