---

- hosts: all
  become: true
  tasks:

  - name: remove testing packages - Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - mariadb-serve
        - samba
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove testing packages - CentOS
    dnf:
      name: 
        - httpd
        - php
        - miriadb
        - samba
      state: absent
    when: ansible_distribution == "CentOS"


