- name: install mariadb package (Ubuntu)
  tags: db,mariadb,centos
  apt:
    name: 
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb package (CentOS)
  tags: ubuntu,db,mariadb
  dnf:
    name: 
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"
